var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/products/ww-brown-rice/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b51d7fce._.js")
R.c("server/chunks/ssr/[root-of-the-server]__df03f1db._.js")
R.c("server/chunks/ssr/node_modules_next_dist_c3d10d89._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b8672bc._.js")
R.c("server/chunks/ssr/app_components_home_124342e6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__2758cdc3._.js")
R.c("server/chunks/ssr/_bf705cba._.js")
R.c("server/chunks/ssr/_adf470e4._.js")
R.m(68184)
R.m(96145)
module.exports=R.m(96145).exports
