var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__f7175bf6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e475b1a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_c3d10d89._.js")
R.c("server/chunks/ssr/_5d70b447._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ea3d7790._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/[root-of-the-server]__779aa2cd._.js")
R.c("server/chunks/ssr/_bf705cba._.js")
R.c("server/chunks/ssr/node_modules_next_dist_57544c01._.js")
R.m(57665)
R.m(70933)
module.exports=R.m(70933).exports
