var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/products/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__27d8baa6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e475b1a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_c3d10d89._.js")
R.c("server/chunks/ssr/_5d70b447._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ea3d7790._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__40089066._.js")
R.c("server/chunks/ssr/_bf705cba._.js")
R.c("server/chunks/ssr/_814353d4._.js")
R.m(37980)
R.m(45401)
module.exports=R.m(45401).exports
