var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/products/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b51d7fce._.js")
R.c("server/chunks/ssr/[root-of-the-server]__df03f1db._.js")
R.c("server/chunks/ssr/node_modules_next_dist_c3d10d89._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b8672bc._.js")
R.c("server/chunks/ssr/app_components_home_124342e6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__40089066._.js")
R.c("server/chunks/ssr/_bf705cba._.js")
R.c("server/chunks/ssr/_814353d4._.js")
R.m(37980)
R.m(45401)
module.exports=R.m(45401).exports
